[package]
name = "example-bat"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.release]
release = false

[dependencies]
jellybean = { path = "../../lib/", features = ["precached"] }
yansi = "1.0.0-rc.1"
