[package]
name = "example-cached"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.release]
release = false

[dependencies]
jellybean = { path = "../../lib/", features = ["serde"] }
bincode = "1.3"
rayon = "1.7"
